# Generated by Django 5.2 on 2025-04-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='password',
        ),
    ]
