# Generated by Django 5.2 on 2025-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0002_remove_registro_de_empresa_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_de_empresa',
            name='senha',
            field=models.CharField(max_length=300),
        ),
    ]
