# Generated by Django 5.2 on 2025-04-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0003_alter_registro_de_empresa_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_de_empresa',
            old_name='senha',
            new_name='password',
        ),
    ]
