# Generated by Django 5.2 on 2025-04-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0005_registro_de_empresa_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='empresa',
        ),
    ]
