# Generated by Django 5.2 on 2025-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registrar_empresa', '0006_remove_registro_de_funcionario_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registro_de_empresa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='password',
        ),
        migrations.AlterField(
            model_name='registro_de_empresa',
            name='nome_da_empresa',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_de_empresa',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='registro_de_empresa',
            name='representante_legal',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_de_funcionario',
            name='date_joined',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_de_funcionario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='registro_de_funcionario',
            name='nome_do_funcionario',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_de_funcionario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
