# Generated by Django 5.2 on 2025-04-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0008_alter_registro_de_empresa_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_de_funcionario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='registro_de_funcionario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registro_de_funcionario',
            name='user_permissions',
        ),
    ]
