# Generated by Django 5.2 on 2025-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0009_alter_registro_de_funcionario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro_de_funcionario',
        ),
        migrations.AlterField(
            model_name='registro_de_empresa',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
