# Generated by Django 5.2 on 2025-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_empresa', '0010_delete_registro_de_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_de_empresa',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registro_de_empresa',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
