# Generated by Django 5.2 on 2025-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_da_empresa', models.TextField(max_length=255)),
                ('nif', models.CharField(max_length=100, unique=True)),
                ('endereco', models.TextField(max_length=255)),
                ('representante_legal', models.TextField(max_length=255)),
                ('email_do_representante', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
