# Generated by Django 5.2 on 2025-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_empresa',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
