# Generated by Django 5.2 on 2025-05-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminpersonalizar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpersonalizar',
            name='campos_personalizados',
        ),
    ]
